# Site settings
url: "//localhost"   # activate this to test on your localhost
author: "BlinkTrade"
baseurl: ""
deploy_version: "HEAD"

exchange: "surbitcoin"
exchange_logo: "surbitcoin"

default_country_code: "VE"
blinktrade_broker_id: 1 # 9 is the id for the demo backend. Don't change that if you don't understand what you doing.

blinktrade_backend_api: "localhost"
google_analytics_id: "UA-56611120-1"
zopim_key: "2YMGhOCdrfa6wpaXqhPAMYewR4gUC2Ee"


# Build settings
markdown: kramdown


languages: ["es", "en_US", "pt_BR", "ro", "zn_CN"]

exclude:     [ "jsdev", "LICENSE", "README.md", "config.rb", "deploy.sh", "build_javascript.sh" ]
source:      .
destination: ./_site
plugins:     ./_plugins
paginate:    5
paginate_path: "post/page:num"
permalink:     /post/:title/
