# Site settings
title: "Blinktrade"
email: "contact@blinktrade.com"
description: "Blinktrade demonstration exchange"
baseurl: ""
author: "BlinkTrade"
keywords: "bitcoin, bitcoin exchange, bitcoin decentralized exchange"
url: "https://pinhopro.github.io"
#url: "//localhost:4000"   # activate this to test on your localhost

social_network_image_share: "/assets/themes/default/img/social_network_share.png"
logo: "/assets/themes/default/img/blink_demo_landing_page_logo.png"
toolbar_logo: "/assets/themes/default/img/blink_demo_landing_page_logo.png"
landing_logo: "/assets/themes/default/img/blink_demo_landing_page_logo.png"

default_country_code: "US"
blinktrade_broker_id: 5  # 5 is the id for the demo backend. Don't change that if you don't understand what you doing.

#blinktrade_backend_api: "api.blinktrade.com"
blinktrade_backend_api: "api.testnet.blinktrade.com"
google_analytics_id: "UA-53856711-1"
zopim_key: "2SSNIzvxy8fBypKoZJ0pI43tUoNCv8os"


# Build settings
markdown: kramdown

languages: ["en_US", "es", "pt_BR"]

exclude:     [ "jsdev", "LICENSE", "README.md", "config.rb" ]
source:      .
destination: ./_site
plugins:     ./_plugins
paginate:    5
paginate_path: "blog/page:num"
permalink:     /blog/:title/
